[versions]
kotlin = "2.4.10"
kotlinx = "1.11.0"
ptotobuf = "4.35.1"
grpc-protobuf = "1.83.1"
grpc-kotlin = "1.5.0"
velocity = "4.1.0-SNAPSHOT"
shadow = "9.6.1"
adventure = "5.2.0"
caffeine = "3.2.4"
spotless = "8.9.0"
fusion = "0.1-SNAPSHOT"
omnivisor = "1.0-SNAPSHOT"
paper = "1.12.2-R0.1-SNAPSHOT"
configurate = "4.2.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
ptotobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "ptotobuf" }
ptotobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "ptotobuf" }
grpc-plugin = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc-protobuf" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc-protobuf" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc-protobuf" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc-protobuf" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-kotlin-plugin = { module = "io.grpc:protoc-gen-grpc-kotlin", version.ref = "grpc-kotlin" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
fusion-api = { module = "io.quut:fusion-api", version.ref = "fusion" }
fusion-velocity = { module = "io.quut:fusion-velocity-api", version.ref = "fusion" }
omnivisor-api = { module = "io.quut:omnivisor-api", version.ref = "omnivisor" }
paper-api = { module = "com.destroystokyo.paper:paper-api", version.ref = "paper" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.10.0" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sponge = { id = "org.spongepowered.gradle.plugin", version = "2.3.0" }
